from machine import Pin, UART, mem32
import machine
import time

# =====================================================
# 1. HARDWARE BASE PERIPHERAL ADDRESS
# =====================================================
I2C1_BASE  = 0x40048000 

# Initialize UART0 to process validation echos
uart = UART(0, baudrate=115200, tx=Pin(0), rx=Pin(1))

# Initialize baseline I2C1 pins to map multiplexer pad lines
i2c_init = machine.I2C(1, sda=Pin(14), scl=Pin(15), freq=100000)

print("[SYSTEM] Configuring RP2040 into Multi-Transaction Clock-Stretched Slave...")
mem32[I2C1_BASE + 0x6C] = 0    # Disable peripheral to apply safely
mem32[I2C1_BASE + 0x00] = 0x22   # Set to Slave Mode, 7-bit addressing, speed default
mem32[I2C1_BASE + 0x08] = 0x50   # Set Slave/Target address to 0x50 (IC_SAR)
mem32[I2C1_BASE + 0x6C] = 1    # Enable engine back onto the silicon layer

# Flush out any leftover garbage or stale bytes from previous runs
while mem32[I2C1_BASE + 0x78] > 0: 
    _ = mem32[I2C1_BASE + 0x10]
if uart.any():
    uart.read()

print("\n=== STARTING TRUE BIDIRECTIONAL SILICON SWEEP (100 CYCLES) ===")
success_count = 0

for index in range(100):
    trigger_byte = (index + 1) & 0xFF
    # Independent payload generated by Object B to send back to Object A
    mock_sensor_reply = (trigger_byte + 0x10) & 0xFF 
    
    print("--------------------------------------------------")
    print(f"TEST {index:02d} | Blasting UART Trigger: 0x{trigger_byte:02X}")
    uart.write(bytes([trigger_byte]))
    
    # --- PHASE 1: Handle Inbound FPGA Write ---
    start_time = time.ticks_ms()
    write_success = False
    captured_write_val = 0x00
    
    while time.ticks_diff(time.ticks_ms(), start_time) < 30:
        # Check IC_RX_FLR (offset 0x78) to see if data landed in FIFO
        if mem32[I2C1_BASE + 0x78] > 0:
            captured_write_val = mem32[I2C1_BASE + 0x10] & 0xFF
            write_success = True
            break
            
    if write_success:
        print(f" -> [I2C Slave] FPGA Write Caught: 0x{captured_write_val:02X}")
    else:
        print(" -> [I2C Slave] Write Timeout Error.")
        continue

    # --- PHASE 2: Handle Outbound FPGA Read Request (With Clock Stretching) ---
    start_time = time.ticks_ms()
    read_success = False
    
    while time.ticks_diff(time.ticks_ms(), start_time) < 30:
        # Poll IC_RAW_INTR_STAT (offset 0x34) Bit 5 to sniff for Master RD_REQ
        if mem32[I2C1_BASE + 0x34] & (1 << 5):
            # Push the sensor payload to the buffer register (automatically drops SCL stretch)
            mem32[I2C1_BASE + 0x10] = mock_sensor_reply
            # Clear the read request interrupt flag
            _ = mem32[I2C1_BASE + 0x50]
            print(f" -> [I2C Slave] Read Request Filled: 0x{mock_sensor_reply:02X}")
            read_success = True
            break

    # --- PHASE 3: Harvest Final Verification Echo over UART ---
    time.sleep_ms(25) # Safe settling window for serial line turnaround
    if uart.any():
        echo_val = uart.read(1)[0]
        print(f" -> [UART RX] Object A Logged Echo: 0x{echo_val:02X}")
        
        if echo_val == mock_sensor_reply:
            print(" >> CYCLE VERIFICATION STATUS: PASS ✅")
            success_count += 1
        else:
            print(" >> CYCLE VERIFICATION STATUS: FAIL ❌ (Data Mismatch)")
    else:
        print(" >> CYCLE VERIFICATION STATUS: FAIL ❌ (UART Silent)")

print("\n==================================================")
print(f" FINAL BENCH BENCHMARK: {success_count}/100 CYCLES PASSED PERFECTLY")
print("==================================================")